### ISSUE TITLE
Advertised hardware sample rate @ 100KSPS?

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/Pixelpulse2#101]
It appears that you are now properly calculating time/frequency in Pixelpulse2 v0.8 using
the 62.5 KSPS that the hardware currently runs at. When is someone going to fix the code
so that the hardware samples at the advertised 100 KSPS? I pointed this difference out
a couple of months ago but nothing has changed.

**Comment by itdaniher** [comment]
Resolved at @bc3d282e2ad1961867e2c09248d5644d2804d04c, requiring a firmware update from https://github.com/analogdevicesinc/m1k-fw/commit/909515e04364dd6e2af3603e33c90dace9024d05.
