### ISSUE TITLE
Missing XY plot for Channel B

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/Pixelpulse2#103]
There's only one XY plot that corresponds to Channel A. 
![missing_second_xy_plot](https://cloud.githubusercontent.com/assets/3383080/6897239/ffa5e990-d6fa-11e4-83b3-61174d71ddc9.jpg)

@itdaniher can you give me a hand with this?

Thanks,
-Dan

**Comment by itdaniher** [comment]
This issue occurs when the xyplot object in https://github.com/analogdevicesinc/Pixelpulse2/blob/master/qml/PlotPane.qml is reset on device detach/attach. The channels are added sequentially, and the first channel (channel A) fills the height of the PlotPane before channel B is added.

The fillheight parameter is set at https://github.com/analogdevicesinc/Pixelpulse2/blob/master/qml/XYPlot.qml#L9. If you comment out that line, and add a property "height:320" the visual glitching ends. I'm working on a dynamic fix without a predefined height value.

**Comment by itdaniher** [comment]
That should do it. Cheers!

**Comment by dNechita** [comment]
Thanks!
