### ISSUE TITLE
optionally increase waveform brightness

### ISSUE THREAD

**Issue by itdaniher** [analogdevicesinc/Pixelpulse2#106]
On mediocre screens, it can be difficult to view the waveform at high zoom levels.

**Comment by kevinmehall** [comment]
When the [point size](https://github.com/analogdevicesinc/Pixelpulse2/blob/ce8c213f489859825b36bb55778f8e0fb7fe741a/qml/SignalRow.qml#L321) hits its maximum, it should start increasing the brightness of the color as you zoom in further.

**Comment by rgetz** [comment]
Sometimes - (on high resolution screens) - it's nearly impossible to see a line one pixel wide. 1080p is fine with the existing setup - new screens are 3840 x 2160 - and it's impossible to see...

Updating to bug.

**Comment by luciansin** [comment]
It happened also to me and I agree with Robin. This is clearly a bug, not an enhancement.

**Comment by jonpearson** [comment]
While not a show-stopper for the labs, this is important in the overall operation.  It would also help when projecting the PixelPulse screen, as we've had difficulty seeing the traces when using a projector.

**Comment by AlexandraTrifan** [comment]
The feature added for issue #176 allows users to manually change the brightness for plots and for the phosphor dot. Should the brightness increase automatically as you zoom in, or is this alright?

**Comment by rgetz** [comment]
Feature #176 fixes this - closing.
