### ISSUE TITLE
Problem with durations over 10ms

### ISSUE THREAD

**Issue by G4DCP** [analogdevicesinc/Pixelpulse2#113]
![win](https://cloud.githubusercontent.com/assets/667018/6993127/36461d9a-dae2-11e4-9577-1c36c02f897b.PNG)

Last few builds seem to abort transfer due to timeouts.

transfer status: LIBUSB_TRANSFER_TIMED_OUT
num_active after cancel:: 0
num_active after cancel:: 1
cancel error in: LIBUSB_SUCCESS / LIBUSB_TRANSFER_COMPLETED out: LIBUSB_SUCCESS
/ LIBUSB_TRANSFER_COMPLETED
OTransfer error LIBUSB_TRANSFER_TIMED_OUT 0xae7a63c
num_active after free:: 0
num_active after free:: 0
ITransfer error LIBUSB_TRANSFER_TIMED_OUT 0xae7a1bc
transfer status: LIBUSB_TRANSFER_TIMED_OUT
num_active after cancel:: 0
num_active after cancel:: 1
cancel error in: LIBUSB_SUCCESS / LIBUSB_TRANSFER_COMPLETED out: LIBUSB_SUCCESS
/ LIBUSB_TRANSFER_COMPLETED
OTransfer error LIBUSB_TRANSFER_TIMED_OUT 0xae7a43c
num_active after free:: 0
num_active after free:: 0
ITransfer error LIBUSB_TRANSFER_TIMED_OUT 0xae7acbc
transfer status: LIBUSB_TRANSFER_TIMED_OUT
num_active after cancel:: 0
num_active after cancel:: 1
cancel error in: LIBUSB_SUCCESS / LIBUSB_TRANSFER_COMPLETED out: LIBUSB_SUCCESS
/ LIBUSB_TRANSFER_COMPLETED
OTransfer error LIBUSB_TRANSFER_TIMED_OUT 0xae7a23c

**Comment by itdaniher** [comment]
Fixed at https://ci.appveyor.com/project/analogdevicesinc/pixelpulse2. Thanks.
