### ISSUE TITLE
Pixelpulse2 fails to run when Qt 5.4 is present on the machine

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/Pixelpulse2#128]
Pixelpulse2 outputs the following on a windows 7 machine that has Qt 5.4 installed on:
![pp2_qt_conflict](https://cloud.githubusercontent.com/assets/3383080/7276829/29e05890-e915-11e4-8054-aeed7bbb226d.png)

Hint: I can make Pixelpulse2 to run if I change the path of the installation of Qt (by changing the Qt folder's name).

**Comment by itdaniher** [comment]
http://stackoverflow.com/questions/16773789/qt5-static-build-yields-failed-to-load-platform-plugin-windows/17271172#17271172

**Comment by itdaniher** [comment]
> QCoreApplication::addLibraryPath("./");

**Comment by itdaniher** [comment]
With the latest build, ["Dependency Walker](www.dependencywalker.com) shows the following for Pixelpulse2.exe:

![image](https://cloud.githubusercontent.com/assets/22683/7277938/a2510e76-e8e0-11e4-8af7-87a53a3182c2.png)

@dNechita Would you be so kind as to run depends.exe on Pixelpulse2 without renaming your Qt folder?

**Comment by dNechita** [comment]
![pp2_dependency](https://cloud.githubusercontent.com/assets/3383080/7292426/52eeed02-e9a4-11e4-9bdc-df3b2bfeb7cd.png)

I'll send you an email with the dependency walker image.

**Comment by itdaniher** [comment]
I have reproduced this issue on my Windows 8 testing laptop. Issue confirmed.

**Comment by dNechita** [comment]
I can confirm that the issue is fixed and I no longer have this problem on my machine.

Thanks!
