### ISSUE TITLE
Parse error on version check

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/Pixelpulse2#137]
![untitled](https://cloud.githubusercontent.com/assets/3383080/7519618/fc0c5cee-f4e9-11e4-8fc6-0354be5e0227.png)

**Comment by itdaniher** [comment]
This looks as if there's a network connectivity problem. Could you get a screenshot of the "About" pane and make sure you can ping github.com?

**Comment by dNechita** [comment]
![about](https://cloud.githubusercontent.com/assets/3383080/7532575/2074ae42-f571-11e4-96a6-c64a49cbafa5.png)
![ping](https://cloud.githubusercontent.com/assets/3383080/7532577/2397ce92-f571-11e4-954e-243aab08a6b8.png)

Also the C implementation of phone home that pixelpulse2 used in the past is working for me. Therefore it doesn't look like a connectivity problem.
