### ISSUE TITLE
Windows doesn't work - graphics problem?

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/Pixelpulse2#145]
Things don't start properly:

![image](https://cloud.githubusercontent.com/assets/1017869/8657770/8b6280fa-296d-11e5-8665-c39d351eaa4d.png)

Any ideas?

**Comment by lrgetz** [comment]
Additional error message.

![error2](https://cloud.githubusercontent.com/assets/13320546/8658308/08502ef2-2971-11e5-82cb-f24731ac1259.PNG)

**Comment by rgetz** [comment]
That looks like a graphics issue, so attaching output from dxdiag.

`
------------------
System Information
------------------
Time of this report: 7/13/2015, 13:27:21
       Machine name: LAUREN-PC
   Operating System: Windows 7 Home Premium 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_gdr.150525-0603)
           Language: English (Regional Setting: English)
System Manufacturer: Dell Inc.
       System Model: XPS L521X
               BIOS: InsydeH2O Version 03.72.24A16
          Processor: Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (4 CPUs), ~3.0GHz
             Memory: 8192MB RAM
Available OS Memory: 8074MB RAM
          Page File: 6683MB used, 9463MB available
        Windows Dir: C:\Windows
    DirectX Version: DirectX 11
DX Setup Parameters: Not found
   User DPI Setting: Using System DPI
 System DPI Setting: 120 DPI (125 percent)
    DWM DPI Scaling: UnKnown
     DxDiag Version: 6.01.7601.17514 32bit Unicode
  DxDiag Previously: Crashed in DirectShow (stage 1). Re-running DxDiag with "dontskip" command line parameter or choosing not to bypass information gathering when prompted might result in DxDiag successfully obtaining this information

------------
DxDiag Notes
------------
      Display Tab 1: No problems found.
        Sound Tab 1: No problems found.
          Input Tab: No problems found.

--------------------
DirectX Debug Levels
--------------------
Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)

---------------
Display Devices
---------------
          Card name: Intel(R) HD Graphics 4000
       Manufacturer: Intel Corporation
          Chip type: Intel(R) HD Graphics Family
           DAC type: Internal
         Device Key: Enum\PCI\VEN_8086&DEV_0166&SUBSYS_054F1028&REV_09
     Display Memory: 1696 MB
   Dedicated Memory: 64 MB
      Shared Memory: 1632 MB
       Current Mode: 1920 x 1080 (32 bit) (60Hz)
       Monitor Name: Generic PnP Monitor
      Monitor Model: unknown
         Monitor Id: AUO00ED
        Native Mode: 1920 x 1080(p) (60.011Hz)
        Output Type: Internal
        Driver Name: igdumd64.dll,igd10umd64.dll,igd10umd64.dll,igdumd32,igd10umd32,igd10umd32
Driver File Version: 8.15.0010.2778 (English)
     Driver Version: 8.15.10.2778
        DDI Version: 11
       Driver Model: WDDM 1.1
  Driver Attributes: Final Retail
   Driver Date/Size: 9/5/2012 18:59:10, 8089088 bytes
        WHQL Logo'd: Yes
    WHQL Date Stamp: 
  Device Identifier: {D7B78E66-4226-11CF-C57F-4225B4C2C435}
          Vendor ID: 0x8086
          Device ID: 0x0166
          SubSys ID: 0x054F1028
        Revision ID: 0x0009
 Driver Strong Name: oem138.inf:IntelGfx.NTamd64.6.0:iIVBM0:8.15.10.2778:pci\ven_8086&dev_0166&subsys_054f1028
     Rank Of Driver: 00E60001
        Video Accel: ModeMPEG2_A ModeMPEG2_C ModeWMV9_C ModeVC1_C 
   Deinterlace Caps: {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
       D3D9 Overlay: Supported
            DXVA-HD: Supported
       DDraw Status: Enabled
         D3D Status: Enabled
         AGP Status: Enabled

-------------
Sound Devices
-------------
            Description: Speakers / Headphones (Realtek High Definition Audio)
 Default Sound Playback: Yes
 Default Voice Playback: Yes
            Hardware ID: HDAUDIO\FUNC_01&VEN_10EC&DEV_0275&SUBSYS_1028054F&REV_1000
        Manufacturer ID: 1
             Product ID: 100
                   Type: WDM
            Driver Name: RTKVHD64.sys
         Driver Version: 6.00.0001.7095 (English)
      Driver Attributes: Final Retail
            WHQL Logo'd: Yes
          Date and Size: 11/20/2013 02:37:50, 3722328 bytes
            Other Files: 
        Driver Provider: Realtek Semiconductor Corp.
         HW Accel Level: Basic
              Cap Flags: 0xF1F
    Min/Max Sample Rate: 100, 200000
Static/Strm HW Mix Bufs: 1, 0
 Static/Strm HW 3D Bufs: 0, 0
              HW Memory: 0
       Voice Management: No
 EAX(tm) 2.0 Listen/Src: No, No
   I3DL2(tm) Listen/Src: No, No
Sensaura(tm) ZoomFX(tm): No

---------------------
Sound Capture Devices
---------------------
            Description: Microphone (USB Audio Device)
  Default Sound Capture: Yes
  Default Voice Capture: Yes
            Driver Name: USBAUDIO.sys
         Driver Version: 6.01.7601.18208 (English)
      Driver Attributes: Final Retail
          Date and Size: 3/17/2014 08:17:19, 109824 bytes
              Cap Flags: 0x1
           Format Flags: 0xFFFFF

            Description: Microphone (Realtek High Definition Audio)
  Default Sound Capture: No
  Default Voice Capture: No
            Driver Name: RTKVHD64.sys
         Driver Version: 6.00.0001.7095 (English)
      Driver Attributes: Final Retail
          Date and Size: 11/20/2013 02:37:50, 3722328 bytes
              Cap Flags: 0x1
           Format Flags: 0xFFFFF

-------------------
DirectInput Devices
-------------------
      Device Name: Mouse
         Attached: 1
    Controller ID: n/a
Vendor/Product ID: n/a
        FF Driver: n/a

      Device Name: Keyboard
         Attached: 1
    Controller ID: n/a
Vendor/Product ID: n/a
        FF Driver: n/a

      Device Name: HID-compliant consumer control device
         Attached: 1
    Controller ID: 0x0
Vendor/Product ID: 0xFEEB, 0xDEEF
        FF Driver: n/a

Poll w/ Interrupt: No

-----------
USB Devices
-----------
+ USB Root Hub
| Vendor/Product ID: 0x8086, 0x1E26
| Matching Device ID: usb\root_hub20
| Service: usbhub
| 
+-+ Generic USB Hub
| | Vendor/Product ID: 0x8087, 0x0024
| | Location: Port_#0001.Hub_#0002
| | Matching Device ID: usb\class_09
| | Service: usbhub

----------------
Gameport Devices
----------------

------------
PS/2 Devices
------------
+ Standard PS/2 Keyboard
| Matching Device ID: *pnp0303
| Service: i8042prt
| 
+ Terminal Server Keyboard Driver
| Matching Device ID: root\rdp_kbd
| Upper Filters: kbdclass
| Service: TermDD
| 
+ Dell Touchpad
| Matching Device ID: *dll054f
| Upper Filters: SynTP
| Service: i8042prt
| 
+ Terminal Server Mouse Driver
| Matching Device ID: root\rdp_mou
| Upper Filters: mouclass
| Service: TermDD

------------------------
Disk & DVD/CD-ROM Drives
------------------------
      Drive: C:
 Free Space: 644.4 GB
Total Space: 693.2 GB
File System: NTFS
      Model:  WD7500BPKX-75HP SCSI Disk Device

      Drive: D:
      Model: MATSHITA DVDRWBD UJ167AM SCSI CdRom Device
     Driver: c:\windows\system32\drivers\cdrom.sys, 6.01.7601.17514 (English), , 0 bytes

--------------
System Devices
--------------
     Name: Intel(R) 7 Series/C216 Chipset Family PCI Express Root Port 1 - 1E10
Device ID: PCI\VEN_8086&DEV_1E10&SUBSYS_054F1028&REV_C4\3&11583659&0&E0
   Driver: n/a

     Name: NVIDIA GeForce GT 640M
Device ID: PCI\VEN_10DE&DEV_0FD2&SUBSYS_054F1028&REV_A1\4&30EB0A7E&0&0008
   Driver: n/a

     Name: Intel(R) USB 3.0 eXtensible Host Controller
Device ID: PCI\VEN_8086&DEV_1E31&SUBSYS_054F1028&REV_04\3&11583659&0&A0
   Driver: n/a

     Name: Intel(R) HD Graphics 4000
Device ID: PCI\VEN_8086&DEV_0166&SUBSYS_054F1028&REV_09\3&11583659&0&10
   Driver: n/a

     Name: Intel(R) 7 Series/C216 Chipset Family USB Enhanced Host Controller - 1E2D
Device ID: PCI\VEN_8086&DEV_1E2D&SUBSYS_054F1028&REV_04\3&11583659&0&D0
   Driver: n/a

     Name: 3rd Gen Core processor DRAM Controller - 0154
Device ID: PCI\VEN_8086&DEV_0154&SUBSYS_054F1028&REV_09\3&11583659&0&00
   Driver: n/a

     Name: Intel(R) 7 Series/C216 Chipset Family USB Enhanced Host Controller - 1E26
Device ID: PCI\VEN_8086&DEV_1E26&SUBSYS_054F1028&REV_04\3&11583659&0&E8
   Driver: n/a

     Name: Xeon(R) processor E3-1200 v2/3rd Gen Core processor PCI Express Root Port - 0151
Device ID: PCI\VEN_8086&DEV_0151&SUBSYS_054F1028&REV_09\3&11583659&0&08
   Driver: n/a

     Name: Synaptics SMBus Driver
Device ID: PCI\VEN_8086&DEV_1E22&SUBSYS_054F1028&REV_04\3&11583659&0&FB
   Driver: n/a

     Name: Killer Wireless-N 1202 (2.4GHz and 5GHz)
Device ID: PCI\VEN_168C&DEV_0034&SUBSYS_20031A56&REV_01\4&3282E3ED&0&00E2
   Driver: n/a

     Name: High Definition Audio Controller
Device ID: PCI\VEN_8086&DEV_1E20&SUBSYS_054F1028&REV_04\3&11583659&0&D8
   Driver: n/a

     Name: Realtek PCIe GBE Family Controller
Device ID: PCI\VEN_10EC&DEV_8168&SUBSYS_054F1028&REV_07\4&48202C2&0&00E0
   Driver: n/a

     Name: Intel(R) Mobile Express Chipset SATA RAID Controller
Device ID: PCI\VEN_8086&DEV_282A&SUBSYS_054F1028&REV_04\3&11583659&0&FA
   Driver: n/a

     Name: Intel(R) 7 Series/C216 Chipset Family PCI Express Root Port 4 - 1E16
Device ID: PCI\VEN_8086&DEV_1E16&SUBSYS_054F1028&REV_C4\3&11583659&0&E3
   Driver: n/a

     Name: SDA Standard Compliant SD Host Controller
Device ID: PCI\VEN_10EC&DEV_5209&SUBSYS_054F1028&REV_01\4&22EB838D&0&01E3
   Driver: n/a

     Name: Intel(R) HM77 Express Chipset LPC Controller - 1E57
Device ID: PCI\VEN_8086&DEV_1E57&SUBSYS_054F1028&REV_04\3&11583659&0&F8
   Driver: n/a

     Name: Intel(R) 7 Series/C216 Chipset Family PCI Express Root Port 3 - 1E14
Device ID: PCI\VEN_8086&DEV_1E14&SUBSYS_054F1028&REV_C4\3&11583659&0&E2
   Driver: n/a

     Name: Realtek PCIE CardReader
Device ID: PCI\VEN_10EC&DEV_5209&SUBSYS_054F1028&REV_01\4&22EB838D&0&00E3
   Driver: n/a

     Name: Intel(R) Management Engine Interface 
Device ID: PCI\VEN_8086&DEV_1E3A&SUBSYS_054F1028&REV_04\3&11583659&0&B0
   Driver: n/a

---------------
EVR Power Information
---------------
Current Setting: {5C67A112-A4C9-483F-B4A7-1D473BECAFDC} (Quality) 
  Quality Flags: 2576
    Enabled:
    Force throttling
    Allow half deinterlace
    Allow scaling
    Decode Power Usage: 100
  Balanced Flags: 1424
    Enabled:
    Force throttling
    Allow batching
    Force half deinterlace
    Force scaling
    Decode Power Usage: 50
  PowerFlags: 1424
    Enabled:
    Force throttling
    Allow batching
    Force half deinterlace
    Force scaling
    Decode Power Usage: 0

`

**Comment by dNechita** [comment]
Might be worth trying to install OpenSSL:
http://slproweb.com/download/Win32OpenSSL_Light-1_0_2d.exe
from page:
http://slproweb.com/products/Win32OpenSSL.html

which should get rid of the SSL related error messages.

-Dan

**Comment by lrgetz** [comment]
That did fix it -- things work now.

I assume that we should be providing 64 and 32 bit versions?
http://indy.fulgan.com/SSL/ ?

Thanks
-Robin

**Comment by dNechita** [comment]
Since Pixelpulse2 is 32-bit compiled I do not think we need the 64-bit version of the SSL library.

**Comment by rgetz** [comment]
Closing this, since it seems to be resolved.
