### ISSUE TITLE
Cannot start PixelPulse2 0.85 and 0.8 on Windows 10

### ISSUE THREAD

**Issue by DanilBorchevkin** [analogdevicesinc/Pixelpulse2#152]
Errors:

![issue](https://cloud.githubusercontent.com/assets/5867045/10471656/e6bb63da-7220-11e5-99ab-94ed4a187302.png)

For 0.8 version nothing only info about QMutex.

System:
Windows 10 Pro Insider Preview 10.0.10547 10547
Intel(R) Celeron(R) CPU G1820 @ 2.70GHz, 2700 МГц
RAM 12 Gb
Nvidia GeForce GTX 650 Ti

**Comment by itdaniher** [comment]
Would you please download distrib.zip and pixelpulse2.exe from https://ci.appveyor.com/project/analogdevicesinc/pixelpulse2/build/0.1.497/artifacts, extract the zip file, place pixelpulse2.exe in the new distrib folder, and run this version?

Your errors look related to the presence of encryption-related files on another drive on your computer. I have not encountered an issue like this before, but recent changes to Pixelpulse2 builds for Windows include the additional cryptography support libraries.

Thanks,
Ian

**Comment by acozma** [comment]
Pixelpulse2 v0.87 is now the recommended version to use on Windows 10. Can you please try that to see if it fixes the issues you've been seeing?

Thanks,
Andrei

**Comment by rgetz** [comment]
We can't replicate, so closing
