### ISSUE TITLE
Resizing windows sometimes corrupts text

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/Pixelpulse2#167]
When resized the windows to a smaller size, the values of frequency/voltage gets overlaid by the side panels:

![image](https://cloud.githubusercontent.com/assets/1017869/14209236/1a08b962-f7f1-11e5-8bc6-895e0517527c.png)

**Comment by jonpearson** [comment]
Not a show-stopper for the summer camp labs, but it would  be good to resolve this soon.

**Comment by luciansin** [comment]
Bug fixed and closed. It was tested with v0.89 and on Win7.32bits, Win7.64bits, Win10.32bits and Win10.64bits.
