### ISSUE TITLE
markers leave plot window when time zooming

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#170]
If you zoom in time domain the markers will leave plot window. For better see this activate Device Manager and/or about

**Comment by jonpearson** [comment]
This is important for the summer camp labs, and should be resolved as quickly as possible.

**Comment by dNechita** [comment]
Fixed with commit https://github.com/analogdevicesinc/Pixelpulse2/commit/ea78f2a547db12fd32c59c9f7f45f82f3b905c6a

**Comment by luciansin** [comment]
Bug fixed and closed. It was tested with v0.89 and on Win7.32bits, Win7.64bits, Win10.32bits and Win10.64bits.
