### ISSUE TITLE
Pixelpulse2 Trace Latchup When M1K Unplugged/Replugged

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/Pixelpulse2#173]
With the system running normally, if the M1K USB cable is unplugged, then plugged back in, the traces freeze when the arrow button is pressed.  The only way I could find to get out of this condition was to close and reopen Pixelpulse2.  The trace latchup condition is illustrated in the following screenshot.

![m1k lockup](https://cloud.githubusercontent.com/assets/18294922/14330532/009070ca-fc0f-11e5-9966-fb454c7ea2a4.jpg)

**Comment by rgetz** [comment]
I think the easiest way to replicate this would be to get something like:

https://www.adafruit.com/products/1620?gclid=Cj0KEQjwrZ24BRC098fr-OqnuMkBEiQAKQ9lgERSbIVjgZgWq1DD1uHZjbS7soIeux4Ny3F0DdNHyvMaAtCs8P8HAQ

and sit there clicking switches. If you need one - please let me know (I ordered some).
-Robin

**Comment by cristi-iacob** [comment]
We have solved this bug and the fix will be available in the next version of the application.
