### ISSUE TITLE
sometimes pixelpulse gets blocked

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#174]
Sometimes when repeated sweep is unchecked, the capture is on with any periodic signal and I change sample time, the application gets frozen with this message appeared in a terminal:
"addr2line is not recognized". 
I wasn't able to read all the message because the terminal became white and pixelpulse was not responding anymore.

**Comment by jonpearson** [comment]
This sounds similar to what I found when checking the long sample time/not filling the screen bug.  I got the same error ("'addr2line' is not recognized as an internal or external command, operable program or batch file.") changing the sample time from 10 s to 1 s.  It happened almost every time when I changed the time scale before changing the sample time to 1 s.  The sequence was:

Launch PP
Press play
Source V
Choose waveform
Change sample time to 10 sec
Wait for screen to fill
Change the displayed time scale
Change sample time to 1 sec
Crash

This happened in both repeated and non-repeated sweep modes.

**Comment by luciansin** [comment]
Using the steps described by Jonathan I was also able to replicate the issue in both repeated and non-repeated modes.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 958465734cbcc53d7ba903ba64072f9803b5ee52.

**Comment by luciansin** [comment]
Bug found, retested and fixed on Win7.64bits. Bug closed.
