### ISSUE TITLE
sometimes signal is not continuous

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#175]
![rep_sweep_unchecked_sampl_time 1s](https://cloud.githubusercontent.com/assets/4027921/14464169/78bcc366-00d6-11e6-8d83-0ea140525114.jpg)
settings:
repeated sweep unchecked
sample_time=1s

**Comment by jonpearson** [comment]
This is the same issue I cited in #172.

**Comment by luciansin** [comment]
this will be closed because it's a duplicate.
