### ISSUE TITLE
restore session doesn't work for channelB waveform

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#179]
I save a session with 2 sinewaves for example on channelA and channelB. Signal frequency is low (50...100Hz). Then I change the waveform type on both channels. And when I restore the previous saved session, the signal type on channelB is not updated.

**Comment by luciansin** [comment]
this only happens sometimes, not every time.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 631b43e707c6ed2fc006d5dc52135ab0dc2b2197.

**Comment by luciansin** [comment]
Bug found, retested and fixed on Win7.64bits. Bug closed.
