### ISSUE TITLE
with a high frequency (>10KHz) signal plotted has a lower amplitude due to sampling rate

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#180]
If I choose a sawtooth from 0V to 5V and a frequency of 50KHz, the signal is from 3.25V to 4.22V and not from 0V to 5V as it should be. A low sampling rate or a low slew rate might be the cause.

**Comment by rgetz** [comment]
Should limit things to 20kHz.

**Comment by dNechita** [comment]
Limiting to 20kHz with commit: https://github.com/analogdevicesinc/Pixelpulse2/commit/cfbdac88f73689a274d6851c37a2c88163b7b8e1
Also the saw-tooth signal was not being generated properly. Fixing with commit: https://github.com/analogdevicesinc/libsmu/commit/383410f777b8fac3e3ded4ce35c49a16b662c5f5

**Comment by luciansin** [comment]
Bug found, retested and fixed on Win7.64bits. Bug closed.
