### ISSUE TITLE
when starting application, no option for sample time is checked 

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#182]
When starting application, no option for sample time is checked in Settings->Sample Time, even if the default one is 100ms.

**Comment by AlexandraTrifan** [comment]
This issue was fixed with commit ac3944df9fb2977ce152f397e3ea8587bce85322 .

**Comment by luciansin** [comment]
Bug found, retested and fixed on Win7.64bits. Bug closed.
