### ISSUE TITLE
in X-Y plots voltage and current axis should be labeled

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#183]
In my opinion, for a better understanding of X-Y plots, we should specify which axis represents voltage and which current. We could label them with I and U. I said this because the axis also change depending if you source voltage or source current. Is that a good idea, to change the axis?

**Comment by AlexandraTrifan** [comment]
Enhancement is now complete. The corresponding commit is: f53f3f697d92b0f8c018b2f8b85229f7c4dd5ec1.

**Comment by luciansin** [comment]
Bug found, retested and fixed on Win7.64bits. Bug closed.
