### ISSUE TITLE
Voltage Measurement Anomaly

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/Pixelpulse2#185]
When sourcing a voltage on Channel A, passing it through a network, and measuring the output voltage on Channel B I observed the following anomaly.  It can be seen on measured current as well.
![m1k measure anomaly 1](https://cloud.githubusercontent.com/assets/18294922/15612053/334bcb5e-23fb-11e6-957e-cd9bd4139fef.jpg)
Changing the time scale works as a workaround, but it would be good to get this resolved soon for the labs.

**Comment by dNechita** [comment]
To solve this a new feature was added. The feature allows user to set an amount of time which will delay the acquisition.

This was added in commit: https://github.com/analogdevicesinc/Pixelpulse2/commit/67a1cb481ec9731390fedfd3c0a038eda4847686

**Comment by luciansin** [comment]
enhancement complete and closed.
