### ISSUE TITLE
Tops of Displayed Waveform Clipped When Set @ 5V

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/Pixelpulse2#186]
The tops of waveforms are clipped on the display when set @ 5V, and a small amount of clipping is seen @ 0V as well; clipping is evident on sourced and measured waveforms as shown below.
![m1k 5v clipped waveform](https://cloud.githubusercontent.com/assets/18294922/15612821/4d392306-23fe-11e6-9a32-eade2f34ea9f.jpg)

**Comment by dNechita** [comment]
Fixed in commit: https://github.com/analogdevicesinc/Pixelpulse2/commit/b22980cbbf0568e7fff8ef5f9cb8af1d7abfc9b4

**Comment by luciansin** [comment]
Bug fixed and closed.
