### ISSUE TITLE
Waveform Measurement Enhancement

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/Pixelpulse2#187]
It would be useful in the labs to have a way to read values directly from the displayed waveforms rather than estimate them from gridlines, and to be able to display common waveform parameters such as peak-to-peak value.  As an example, in the filter lab it is necessary to find the 3 dB frequency, and it would be good to be able to display the output peak-to-peak voltage to determine this.

**Comment by dNechita** [comment]
Peak-to-peak, frequency, RMS (maybe).
Even if peak-to-peak and frequency are being shown when sourcing current or voltage it is required to have the measurements for the setup when voltage is being measured (high impedance).

-Dan

**Comment by AlexandraTrifan** [comment]
Enhancement is now complete. The corresponding commit is  28adda26c2d59e008e1e836fb5bff5de7a282cd9.

**Comment by luciansin** [comment]
Peak-to peak and RMS values added. Do we want something else added as well?

**Comment by luciansin** [comment]
enhancement complete and closed.
