### ISSUE TITLE
incorrect version in about

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#188]
The version specified in about is a wrong one. For this release you have this:
![about](https://cloud.githubusercontent.com/assets/4027921/15677520/4ddaad04-2753-11e6-9a92-9082ea9148a7.png)

**Comment by dNechita** [comment]
Fixed both Windows and  Mac OS builds.

**Comment by luciansin** [comment]
bug fixed and closed.
