### ISSUE TITLE
bad plot when restoring a session in maximum size window

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#189]
steps to reproduce:
1. save session from a default size Pixelpulse window like this: 
![pic1](https://cloud.githubusercontent.com/assets/4027921/15710932/c1bf01d6-2814-11e6-93a1-7e4adc6af74f.png)
2. close and restart application and maximaze Pixelpulse window
3  restore previous saved session. It will look like this, the signal won't fill the entire window:
![pic2](https://cloud.githubusercontent.com/assets/4027921/15711114/60ce4cd2-2815-11e6-977d-2bddda8b1fe3.png)

**Comment by AlexandraTrifan** [comment]
Fixed with commit 1c468d3a40d050e41355361edda36c800a387bd2.

**Comment by luciansin** [comment]
Bug retested and fixed in ubuntu 16.04 LTS. 
Not able to retest in windows and mac os yet.

**Comment by luciansin** [comment]
Bug retested and fixed also on windows and mac os. Bug closed.
