### ISSUE TITLE
restore session doesn't restore X-Y plots

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#190]
steps to reproduce:
1. save a session with X-Y plots checked
2. restore that session

in restored session X-Y plots won't be checked. (it's the same with about and device manager)

**Comment by AlexandraTrifan** [comment]
This is not necessarily a bug because pixelpulse did not have this feature. It can be labeled as an enhancement. 
Do we want this to be implemented?

**Comment by AlexandraTrifan** [comment]
Enhancement complete. (commit c2f8ade751c4cd9323987bbf6816209d572cc42c)
Only the X-Y plots option is restored now. Do we want to restore about and device manager as well?

**Comment by luciansin** [comment]
X-Y plots option is restored now. In order be able to close this enhancement and consider it complete, someone please answer Alexandra question.

**Comment by rgetz** [comment]
No - device manager, and about can stay closed.

**Comment by luciansin** [comment]
enhancement complete and closed.
