### ISSUE TITLE
left marker can be overlaid by "voltage" label

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#191]
when X-Y plots, about and device manager are checked and you resize the window to smallest left marker can be overlaid by "voltage" label or can't be seen entirely(if it's down).
![pic3](https://cloud.githubusercontent.com/assets/4027921/15714356/e0307466-2822-11e6-8a4f-2d5f1425f04d.png)

**Comment by AlexandraTrifan** [comment]
Fixed with commit 83378fcbd8ae1299e62f5ca7ff3e8b231e303067.

**Comment by luciansin** [comment]
Bug retested and fixed in ubuntu 16.04 LTS. 
Not able to retest in windows and mac os yet.

**Comment by luciansin** [comment]
Bug retested and fixed also on windows and mac os. Bug closed.
