### ISSUE TITLE
Pixelpulse (or libsmu?) doesn't handle suspend/resume

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/Pixelpulse2#192]
While device is attached, and streaming - go into S3, unplug, turn on, PixelPulse crashes.

Files that help describe the problem:
  C:\Users\rgetz\AppData\Local\Temp\WERC19.tmp.WERInternalMetadata.xml
  C:\Users\rgetz\AppData\Local\Temp\WER221C.tmp.appcompat.txt
  C:\Users\rgetz\AppData\Local\Temp\WER227B.tmp.mdmp

File is actually a .7z (but github doesn't like those - just rename).
[crash.zip](https://github.com/analogdevicesinc/Pixelpulse2/files/296318/crash.zip)

**Comment by cristi-iacob** [comment]
We have solved this bug and the fix will be available in the next version of the application.
