### ISSUE TITLE
pixelpulse stops responding sometimes 

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#193]
Sometimes when not using "repeated sweep", and changing from any sample time to "10s - sample time", pixelpulse stops responding(it gets blocked), after it runs for a while. It happens on both Windows7 and Windows10(more often on Windows10).

**Comment by luciansin** [comment]
In order to better reproduce the bug, you can zoom in then zoom out maximum in time domain.

**Comment by luciansin** [comment]
This happens also with any periodic signal when with repeated sweep checked, you change sample time to 10s, wait for the screen to fill in then uncheck repeated sweep. After these actions Pixelpulse will stop responding. I think the application "doesn't like" the combination repeated sweep unchecked and sample time 10s.

**Comment by cristi-iacob** [comment]
Couldn't reproduce the bug on Windows 10 and Ubuntu 18.04.
