### ISSUE TITLE
an error message should appear when not able to update firmware anymore 

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#194]
an error message should appear when not able to update firmware anymore because of too many firmware updates during one hour. This is what appears now:
![pic1](https://cloud.githubusercontent.com/assets/4027921/15817964/6ed87be6-2be3-11e6-923b-0066f6b5802f.png)

**Comment by dNechita** [comment]
Such a message will be displayed starting from commit: https://github.com/analogdevicesinc/Pixelpulse2/commit/f1f9309fa64ecdd8a773611edac04f153f8fb627

**Comment by luciansin** [comment]
bug fixed and closed.
