### ISSUE TITLE
sometimes pixelpulse firmware fails to update

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#196]
steps to reproduce:
1.	Plug M1K in PC.
2.	Close pixelpulse
3.	Open bossa and write an older firmware version.
4.	Close bossa.
5.	Unplug and replug the device in PC. Pixelpulse will automatically open.
6.	Press on “update firmware” button: update will fail.
7.	Close and reopen Pixelpulse(keep the device pluged), then press on “update firmware” button: update will work.

for windows,64bits:
![firmware_update_64bits](https://cloud.githubusercontent.com/assets/4027921/15926971/7eaed52c-2e47-11e6-9c25-2132c6ed7e92.png)

for windows,32bits:
![firmware_update_32bits](https://cloud.githubusercontent.com/assets/4027921/15926983/96fe7998-2e47-11e6-9b69-81c41ac10d57.png)

**Comment by dNechita** [comment]
Fixed in https://github.com/analogdevicesinc/Pixelpulse2/commit/c9f0a5873d0b862bf8de6fc4f4f1c6684ba7f751

**Comment by luciansin** [comment]
bug fixed and closed.
