### ISSUE TITLE
white active menu in ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#198]
steps to reproduce:
choose any option from any menu from pixelpulse window then activate that menu again

actual behavior:
Active menu is white. After a new right click the menu will be displayed correctly.

This happens for all type of menus in pixelpulse window:
1.settings menu:
![screenshot from 2016-06-13 18-02-06](https://cloud.githubusercontent.com/assets/4027921/16006187/54a51d60-3174-11e6-9f29-c73cd1d6b1cc.png)
2.channel type menu:
![screenshot from 2016-06-13 18-12-25](https://cloud.githubusercontent.com/assets/4027921/16006213/6aeb6bc4-3174-11e6-9a1f-cf59c8bc7edc.png)
3.waveform type menu:
![screenshot from 2016-06-13 18-07-50](https://cloud.githubusercontent.com/assets/4027921/16006236/910e9d94-3174-11e6-9ef6-8bd9b5dcc62f.png)

This only happens in Linux (Ubuntu 16.04 LTS)

**Comment by luciansin** [comment]
the warning in terminal is: 
libpng warning: iCCP: known incorrect sRGB profile

**Comment by luciansin** [comment]
same thing happens with Sample Time menu.

**Comment by cristi-iacob** [comment]
Couldn't reproduce the bug on Windows 10 and Ubuntu 18.04.
