### ISSUE TITLE
pixelpulse stops responding when connecting a new device on a PC with ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#200]
steps to reproduce:
1.connect one M1K device to a PC with ubuntu 16.04 LTS installed.
2.start pixelpulse from terminal after building it
3.attach another M1K device to same PC and press "Refresh Device List" button

After these steps, Pixelpulse will freeze and not respond anymore.

**Comment by luciansin** [comment]
If you connect both devices before starting pixelpulse, and afterwards start pixelpulse, it works.

**Comment by itdaniher** [comment]
Is this related to https://github.com/analogdevicesinc/libsmu/issues/113, perhaps?

**Comment by cristi-iacob** [comment]
We have solved this bug and the fix will be available in the next version of the application.
