### ISSUE TITLE
only integer values can be set for the frequency of a periodic signal

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#204]
Even if frequency value has 3 fractional zeros, you cannot set a fractional frequency for a periodic signal. For fractional values from 0.0 to 0.499 the frequency value remains the same, for values from 0.500 to 0.999 the frequency value increases by 1.

**Comment by AlexandraTrifan** [comment]
Fixed with commit 4aa143af3c9bea6c22bf918a7ff849b5c68d7db3.

**Comment by AlexandraTrifan** [comment]
Fixed on v1.0.4. Closing this issue.
