### ISSUE TITLE
RMS reading on constant source with repeated sweep checked and unchecked

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/Pixelpulse2#207]
Setup:
-A resistor is connected for each channel (between Channel A and GND and Channel B and GND).
-Channel A is configured as Source Voltage, Measure Current.
-Channel B is configured as Source Current, Measure Voltage.
-PixelPulse2 v0.90 on Windows 7 x64

Issue:
-When the repeated sweep is **checked**, there's no RMS reading for each channel (No Current reading on CHA and no voltage reading on CHB).
-When the repeated sweep is **unchecked**, the RMS reading is valid.
-The same behavior happens when Channel A is configured as Source Current, Measure Voltage and Channel B is configured as Source Voltage, Measure Current.
-The same behavior also occurs when measuring voltages from external constant source.

![constant source at repeated sweep checked](https://cloud.githubusercontent.com/assets/20266602/17234525/6cf00dbe-556c-11e6-92ae-2f4a97f80409.JPG) 
_repeated sweep checked_

![constant source at repeated sweep unchecked](https://cloud.githubusercontent.com/assets/20266602/17234535/7cbb11bc-556c-11e6-88db-1c39a29434ed.JPG)
_repeated sweep uchecked_

**Comment by cristi-iacob** [comment]
I cannot reproduce the bug. I've tried on Windows 7 on 32 and 64 bits, Windows 10 on 64 bits and Ubuntu 18.04.
