### ISSUE TITLE
serialisation / restore of sessions

### ISSUE THREAD

**Issue by itdaniher** [analogdevicesinc/Pixelpulse2#21]
It'd be great if teachers could distribute a serialized configuration (ie: lab1.json) to students, further lowering the barrier to entry / use.

There are 71 properties in the qml for pixelpulse2, so a naive implementation (adding save/restore hooks to all Items) would be pretty onerous.

**Comment by rgetz** [comment]
setup should be persistent configurations across device detach / reattach (in same session), or between sessions (open/close pixelpulse).

**Comment by itdaniher** [comment]
Turns out this won't be as hard to implement as I had feared. session.devices.channels.signals is a pretty dense representation of current configuration.

**Comment by itdaniher** [comment]
@dNechita session.devices[0].channels[0].signals

**Comment by itdaniher** [comment]
Now: deviceRepeater.itemAt(0).channelRepeater.itemAt(0).signalRepeater.itemAt(0).signal

**Comment by itdaniher** [comment]
``` js
// variable to store signal configurations
var y = StateSave.saveState();
// change yaxis-max to 3.0
y[0].ymax=3.0;
// restore session
StateSave.restoreState(y);
```
should be working shortly...

**Comment by itdaniher** [comment]
Okay, it's actually:

``` js
var y = StateSave.saveState();
y["0A_Voltage"].ymax=3;
StateSave.restoreState(y);
```
