### ISSUE TITLE
Direct Entry of Upper and Lower Display Limits

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/Pixelpulse2#211]
It would be good to be able to set the upper and lower limits in measurement and source modes in addition to scrolling with the right mouse button.  This feature would allow waveforms, such as the input and output levels of an amplifier, filter, etc..., to be compared more accurately because the volts/div and amps/div settings could be made to be exactly the same for both channels.

**Comment by cristi-iacob** [comment]
Feature implemented. You can change these limits by changing the values of MinA/MaxA and MinV/MaxV. Thanks!
