### ISSUE TITLE
[wiki]- ADALM1000 Design Document Dead Link

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/Pixelpulse2#215]
From [https://wiki.analog.com/university/tools/m1k/design](url) site, there's a dead link under the Sample Rate section.

I attached a pdf file to point out the link easily, it's on page 3.
[ADALM1000 Design Document [Analog Devices Wiki].pdf](https://github.com/analogdevicesinc/Pixelpulse2/files/698080/ADALM1000.Design.Document.Analog.Devices.Wiki.pdf)

**Comment by rgetz** [comment]
Fixed - thanks for pointing out.
