### ISSUE TITLE
libsmu must be installed before Pixelpulse compiles.

### ISSUE THREAD

**Issue by itdaniher** [analogdevicesinc/Pixelpulse2#222]
attempting to install as per the readme gives the error: 

> Project ERROR: libsmu development package not found

It was not obvious, but libsmu must be compiled and `make install`'d into /usr/local or equiv separately from Pixelpulse.

The readme says "After it is finished building,you have to copy the libsmu shared library into the build folder and Pixelpulse2 should be ready to use with your M1K"

**Comment by claudiupop** [comment]
This commit af41df256ca2f3c5d333930c90e2e22160c6bb82 should make it clear to build and install libsmu before trying to install pixelpulse.

**Comment by itdaniher** [comment]
Thanks!
