### ISSUE TITLE
Pixelpulse2 broken with firmware 023314a, firmware won't update

### ISSUE THREAD

**Issue by itdaniher** [analogdevicesinc/Pixelpulse2#223]
I press "Play" and get the following:

![2018-02-01-123709_963x1059_scrot](https://user-images.githubusercontent.com/22683/35693594-a680bea0-074c-11e8-8057-6727f5ddf9aa.png)

Clicking "Update Firmware" in the device manager pane prints "0: failed to open firmware file," the M1K does not enter bootload mode, and PP2 must be restarted to recognize the device.

![2018-02-01-123847_964x1057_scrot](https://user-images.githubusercontent.com/22683/35693671-dd6bb352-074c-11e8-8cf3-646572963fa2.png)

**Comment by claudiupop** [comment]
Could you tell me on which operating system are you experiencing this issue ?

Thanks

**Comment by itdaniher** [comment]
@claudiupop fully updated Ubuntu 17.10 "artful" on x86_64

**Comment by AlexandraTrifan** [comment]
After this commit 59f7df9176cf93323335b07cc25bb447ca33a584 you should be able to update the firmware.

**Comment by itdaniher** [comment]
Does the trick. Many thanks!
