### ISSUE TITLE
add snap to X and Y axes

### ISSUE THREAD

**Issue by itdaniher** [analogdevicesinc/pixelpulse2#23]
hold control, click and drag - snaps to a regular number of mv/ma, integer multiples / fractions of the phase/frequency of the other waveforms.

**Comment by itdaniher** [comment]
prototyped at 07c95377741abe32f42bb8adbf5982b0e08a83df

**Comment by kevinmehall** [comment]
Is this closed to your satisfaction, or are we leaving this open so that we improve X-axis snap in the future?

**Comment by itdaniher** [comment]
calling this good.
