### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by Jobsbu** [analogdevicesinc/Pixelpulse2#258]
Hi, I followed the instruction to download libsmu on MacOS from https://github.com/analogdevicesinc/libsmu and when I try to run Pixelpulse2 I encountered the following error:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND. Please set them or make sure they are set and tested correctly in the CMake files: LIBSMU_LIBRARIES
<img width="831" alt="Screenshot 2022-06-23 at 08 03 06" src="https://user-images.githubusercontent.com/108061131/175267981-031dfa88-ca8b-4c9b-bb4f-7a012c2e06b8.png">

Do you have any idea why the error occurred? 
Any help is appreciated.

**Comment by AlexandraTrifan** [comment]
Hi,

I added a minor change on a separate branch, can you try to build that one and check whether it works?
https://github.com/analogdevicesinc/Pixelpulse2/tree/find_libsmu_fix

Thank you!
-Alexandra
