### ISSUE TITLE
resistance measurement / basic math

### ISSUE THREAD

**Issue by itdaniher** [analogdevicesinc/Pixelpulse2#26]
UI should expose some rudimentary method to measure resistances, possibly expanded to arbitrary impedances.

**Comment by ragingSloth** [comment]
basic VNA capabilities?

**Comment by itdaniher** [comment]
Expanding from DC resistance measurements to impedance-over-frequency measurements does in fact handle a decent amount of the backend for VNA functionality. It's worth noting that the set of data representations often used for VNA measurements doesn't share much with the set of representations used for lower-frequency impedance measurements. IE) bode plots != smith plots

**Comment by itdaniher** [comment]
1cb8a8e963cc85ba75f24575b274717aaec45485
