### ISSUE TITLE
package for OSX

### ISSUE THREAD

**Issue by itdaniher** [analogdevicesinc/pixelpulse2#45]

**Comment by rgetz** [comment]
I think Tim was working on this - so -- Tim - Any updates?

**Comment by radhermit** [comment]
I've got a dmg image fully working just wondering where to put it.

**Comment by rgetz** [comment]
Can you put it on the wiki for now.

Thanks
- Robin

On Feb 23, 2015, at 7:58 PM, Tim Harder <notifications@github.com<mailto:notifications@github.com>> wrote:


I've got a dmg image fully working just wondering where to put it.

�

**Comment by itdaniher** [comment]
@radhermit 's changes have been merged. OSX package at https://github.com/analogdevicesinc/pixelpulse2/releases.

**Comment by radhermit** [comment]
Closing this since the package should work. I'll redo the package when the libsmu submodule is updated with the required changes.
