### ISSUE TITLE
higher contrast color scheme

### ISSUE THREAD

**Issue by itdaniher** [analogdevicesinc/pixelpulse2#5]
Pp2 is as dark as pp1 was light. Inverting all colors would improve readability on crap displays. Better yet, improving the contrast of text and data on background would improve UX.

**Comment by itdaniher** [comment]
http://tango.freedesktop.org/Tango_Icon_Theme_Guidelines

**Comment by ralphrmartin** [comment]
Dark grey plot labels on black background are pretty much illegible. Need white on black for all UI elements.

**Comment by itdaniher** [comment]
"It's almost impossible to read the axes on the plots though - dark gray on black is not the best combination. Can we please have white on black for ALL the annotations?"

**Comment by itdaniher** [comment]
Great minds - thanks, @ralphrmartin!

**Comment by itdaniher** [comment]
Text is now white at 18a5063. The next binary releases of Pixelpulse2 will address this.
