### ISSUE TITLE
Density gradiated?

### ISSUE THREAD

**Issue by kuldeepdhaka** [analogdevicesinc/pixelpulse2#54]
How is "OpenGL accelerated density-gradiated rendering" being done?
as per the source:
 https://github.com/analogdevicesinc/pixelpulse2/blob/master/Plot/PhosphorRender.cpp#L13
https://github.com/analogdevicesinc/pixelpulse2/blob/master/Plot/PhosphorRender.cpp#L22
gradient height is not dependent on sample values.

reference: http://www.tek.com/blog/sample-processing-digital-oscilloscope

**Comment by kevinmehall** [comment]
All samples are displayed as translucent points, and their brightness is additive with `glBlendFunc(GL_ONE, GL_ONE)`. Thus pixels containing more sample points are brighter.

**Comment by itdaniher** [comment]
@kuldeepdhaka closing this issue with @kevinmehall's answer. Feel free to open additional issues questions and comments. Thanks!
