### ISSUE TITLE
Lower Drag Dot can be dragged out of the horizontal bounds

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/pixelpulse2#74]
While drag dots positions are limited on the vertical axis (ranging from 0.0V to 5.0V), on the horizontal axis there is no limit on both left and right edges.
Therefore the dot exceeds both the plot frame and the application window.
This applies to the lower dot of the dot pair which is available for all types of signals except for "Constant" where there is only one available dot movable only on the vertical axis.

Downfalls:
 - the dot overlaps with other GUI elements which damages esthetics.
 - the position of the dot can be lost (not visible anymore) if the dot gets dragged out of the window.

![pp2_dragdot_out_of_bounds](https://cloud.githubusercontent.com/assets/3383080/6616610/5975b0c8-c8b8-11e4-97c6-3b0f536047e1.jpg)

**Comment by itdaniher** [comment]
https://github.com/analogdevicesinc/pixelpulse2/commit/1b327913300b56217cc81b51405bb58c0c59a39d

**Comment by itdaniher** [comment]
Resolved this by checking xaxis.width in the onDrag handlers for DragDots.
