### ISSUE TITLE
Appveyor Windows version has old dependancy zip file.

### ISSUE THREAD

**Issue by G4DCP** [analogdevicesinc/pixelpulse2#77]
Current pixelpulse2.exe requires libcurl & libJannsson-4.

I tried obtaining the missing dll's (maybe I have wrong versions).
  It then crashes when trying to check for an update.

**Comment by G4DCP** [comment]
I have tried checking today the dist zip is still missing files for libcurl and libjannsson-4
![crash](https://cloud.githubusercontent.com/assets/667018/6692050/335988f2-ccc2-11e4-979e-595bb2e95218.PNG)
The attached image shows what happens when I run the latest exec with the dist zip and what I hope are the correct DLL's. 
Please can someone look at this problem.

**Comment by dNechita** [comment]
Yes, I'll take a look at this and try to fix it in the next couple of hours.

Until then, could you please use the 0.1.175 build?
https://ci.appveyor.com/project/analogdevicesinc/pixelpulse2/build/0.1.175/artifacts

Thanks for reporting this and sorry for the inconvenience.

-Dan

**Comment by G4DCP** [comment]
Using 0.1.175 is much less likely to crash than the version in the builds area.

Looking forward to the latest version.

**Comment by dNechita** [comment]
Things should be working now.

-Dan

**Comment by G4DCP** [comment]
I can confirm that it does work!
