### ISSUE TITLE
Add shif

### ISSUE THREAD

**Issue by G4DCP** [analogdevicesinc/pixelpulse2#80]

**Comment by itdaniher** [comment]
@G4DCP Feel free to reopen with the rest of your suggestion. Thanks!

**Comment by G4DCP** [comment]
Oh ouch!
It has lost the entire message!

In the scope sections of the display you can use shift drag and drag to move the viewpoint.
You can also use  to the middle zoom wheel to scale the x axis and shift zoom to scale the y axis and that is very intuitive.
In the plot section of the display which can be optionally turned on zoom and shift zoom work well.
Unfortunately drag and shift drag do not have any effect on the viewpoint. Which is a pity.

Sorry I somehow managed to loose my origional post!

**Comment by G4DCP** [comment]
Please see issue 81
