### ISSUE TITLE
LED indicator 

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/pixelpulse2#86]
Although a interesting idea, the concept of being able to identify units via the color of the LED, doesn't seem to work.

If we assume an "active" channel by the one that the user is controlling in the GUI, (or last changed), we can blink the channel colour that is active on that unit.

That might mean firmware, libsmu, or GUI changes.

-Robin

**Comment by itdaniher** [comment]
Duplicate of https://github.com/analogdevicesinc/pixelpulse2/issues/78, but this is a better problem statement than my overly technical issue.

**Comment by rgetz** [comment]
OK - closing this, since I missed it.
