### ISSUE TITLE
Documentation is lacking

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/Pixelpulse2#88]
Documentation (on wiki) on firmware and host code.

should be structured from:

GUI (end user instructions)
http://wiki.analog.com/university/tools/m1k/pixelpulse

How to build from source:
http://wiki.analog.com/university/tools/m1k/pixelpulse/build

Pixelpulse documentation (for people who want to hack on Pixelpulse )
http://wiki.analog.com/university/tools/m1k/pixelpulse/internals

Firmware documentation (for people who want to hack on firmware)
http://wiki.analog.com/university/tools/m1k/firmware

libsmu documentation (for people who want to hack on firmware)
http://wiki.analog.com/university/tools/m1k/libsmu

**Comment by AlexandraTrifan** [comment]
Documentation is up to date. Closing this.
