### ISSUE TITLE
Doxygen from pixelpulse/libsmu/firmware

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/Pixelpulse2#89]
Code should be written in Linux kernel coding style, and have support for auto-generated documentation via Doxygen.

The Doxygen should be autogenerated in github.

**Comment by itdaniher** [comment]
@dbogdan What modifications are required to the source/comment syntax to improve the Doxygen docs?

**Comment by AlexandraTrifan** [comment]
libsmu Doxygen docs are available on gh-pages.
http://analogdevicesinc.github.io/libsmu/

Closing this.
