### ISSUE TITLE
Correct Githup Readme to make life easier for inexperienced people.

### ISSUE THREAD

**Issue by G4DCP** [analogdevicesinc/pixelpulse2#93]
Currently the following paragraph in the readme is misleading.

Windows - Download the dependency package and the latest binary build. Extract the dependency package and overwrite the included pixelpulse2.exe with the latest build downloaded from AppVeyor.

The words dependency package are linked to broken link.  I believe the users should be told to download the dist.zip from the other link (on binary build).

**Comment by itdaniher** [comment]
Thanks for the suggestions! I edited the readme. We'll revise the documentation shortly, as we suggest installers for all platforms.
