### ISSUE TITLE
distrib.zip has disappeared from AppVeyor!

### ISSUE THREAD

**Issue by G4DCP** [analogdevicesinc/pixelpulse2#94]
Just as the readme was changed AppVeyor no longer includes the distrib.zip!!!

**Comment by G4DCP** [comment]
From AppVeyor log.

Compressing distrib\zlib1.dll
 
Everything is Ok
appveyor PushArtifact distrib.zip
Error pushing artifact: The request was aborted: The request was canceled.
Command exited with code 2

**Comment by itdaniher** [comment]
Good news is that distrib.zip isn't changed often. I'm not sure why the Appveyor build was canceled, but the distrib.zip at https://github.com/analogdevicesinc/pixelpulse2/releases/tag/v0.8 will work for now!
