### ISSUE TITLE
Pixelpulse 2 v0.80 graphical rendering

### ISSUE THREAD

**Issue by shintorl** [analogdevicesinc/Pixelpulse2#98]
On both of my Win7 Dell Laptops, the text is rendered incorrectly. 

![pixelpulse2-v080](https://cloud.githubusercontent.com/assets/11620530/6791118/16752438-d183-11e4-897f-25f31f17b171.png)

**Comment by itdaniher** [comment]
Thanks for reporting this issue! We'll look into it.

**Comment by itdaniher** [comment]
@shintorl Could you check with Pixelpulse2.exe and distrib.zip from https://ci.appveyor.com/project/analogdevicesinc/pixelpulse2/build/0.1.377/artifacts? I have not been able to reproduce this issue on any of the devices I've tried.

Thanks!
